[package]
name = "sorteador_de_livros_para_ler"
version = "0.1.0"
authors = ["gabriel souza <gabrielsouza849@gmail.com>"]

[dependencies]
diesel = { version = "1.4.1", features = ["sqlite"] }
commander = "0.1.2"
dotenv = "0.13.0"


